### PR TITLE
Add failing tests

### PR DESCRIPTION
**Pull request by Guiguiprim**
Second attempt, this time I'm pretty sure there is a normal dependency.

### CODE REVIEW

**Comment by sunshowers** [comment]
Thanks so much, let me have a look

**Comment by sunshowers** [comment]
Ahhhh! So it looks like you're using the `--no-deps` graph, which doesn't work with dependency calculations. If you remove `--no-deps` from the nextest graph query, it should work!

**Comment by Guiguiprim** [comment]
So bad usage from my part, sorry for the inconvenience.

**Comment by sunshowers** [comment]
> So bad usage from my part, sorry for the inconvenience.

No, not at all -- this is quite confusing, the main reason for `--no-deps` is performance but we definitely lose out on functionality that way. (I think the performance issues still stand, so we probably need to do something like inspect the expression to see if we need dependency information before querying the graph. This can be done with a little care I think).

**Pull request closed without merging**
